networks:
  colocus-network:
    driver: bridge

volumes:
  postgres_data:

services:
  db:
    image: postgres:16
    container_name: colocus-db
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bin/init-postgres.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - colocus-network

  redis:
    image: redis:8
    container_name: colocus-redis
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - colocus-network

  django:
    image: ghcr.io/statgen/colocus:latest
    container_name: colocus-django
    restart: always
    env_file: .env
    volumes:
      - "${DATA_PATH}:/data:ro"
    ports:
      - "${UVICORN_PORT}:${UVICORN_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${UVICORN_PORT}/api/v1/datasets/?page_size=1"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - colocus-network

  ui:
    image: ghcr.io/statgen/colocus-ui-vue3:latest
    container_name: colocus-ui
    restart: always
    env_file: .env
    volumes:
      - ./etc/nginx/colocus.conf.template:/etc/nginx/templates/colocus.conf.template
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${UI_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${UI_PORT}:${UI_PORT}"
    depends_on:
      django:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - colocus-network
