# Generated by Django 4.2.9 on 2024-11-15 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.TextField(
                        help_text="A stable unique identifier for this dataset, should be specified on ingest",
                        unique=True,
                    ),
                ),
                (
                    "analysis_type",
                    models.TextField(
                        choices=[("GWAS", "GWAS"), ("eQTL", "eQTL")],
                        help_text="Type of association analysis - GWAS, eQTL, pQTL, ATAC-seq, methylation, etc.",
                    ),
                ),
                (
                    "genome_build",
                    models.TextField(
                        choices=[("GRCh37", "GRCh37"), ("GRCh38", "GRCh38")],
                        help_text="Genome build used for all analyses in this dataset",
                    ),
                ),
                (
                    "n_traits",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of traits analyzed in this dataset"
                    ),
                ),
                (
                    "n_traits_with_sig",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of traits with at least one signal"
                    ),
                ),
                (
                    "tissue",
                    models.TextField(
                        blank=True,
                        help_text='Tissue type for all analyses in this dataset (if applicable), e.g. "adipose" or "liver"',
                        null=True,
                    ),
                ),
                (
                    "ancestry",
                    models.TextField(
                        blank=True,
                        help_text='Ancestry of the samples used for analyses in this dataset, e.g. "EUR"',
                        null=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact of record to report problems / questions about this dataset",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True,
                        help_text="URL for where the data was downloaded from. Used to track provenance.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.TextField(
                        help_text="A stable unique identifier for this dataset, should be specified on ingest",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text='A human-readable description of the dataset, like "Colocalization & fine-mapping of adipose eQTLs"',
                        null=True,
                    ),
                ),
                (
                    "ingest_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when this dataset was loaded into the site",
                        null=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact of record to report problems / questions about this data submission",
                        max_length=254,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ens_id",
                    models.TextField(
                        db_index=True,
                        help_text="Ensembl ID of the exon, or Ensembl ID of the gene + exon coordinates, e.g. ENSG00000141510.15_1_100",
                        unique=True,
                    ),
                ),
                ("chrom", models.TextField(help_text="Chromosome", null=True)),
                (
                    "start",
                    models.PositiveIntegerField(
                        help_text="Start position of the exon", null=True
                    ),
                ),
                (
                    "end",
                    models.PositiveIntegerField(
                        help_text="End position of the exon", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FineMappingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text='Name of the fine-mapping program, e.g. "SuSiE" or "FINEMAP"'
                    ),
                ),
                (
                    "version",
                    models.TextField(
                        help_text='Version of the fine-mapping program, e.g. "v1.0.0"',
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ens_id",
                    models.TextField(
                        db_index=True, help_text="Ensembl ID", unique=True
                    ),
                ),
                ("symbol", models.TextField(db_index=True, help_text="HGNC symbol")),
                ("chrom", models.TextField(help_text="Chromosome", null=True)),
                (
                    "start",
                    models.PositiveIntegerField(
                        help_text="Start position of the gene", null=True
                    ),
                ),
                (
                    "end",
                    models.PositiveIntegerField(
                        help_text="End position of the gene", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LDStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.TextField(
                        db_index=True,
                        help_text="A stable unique identifier for this entity. Should be specified on ingest.",
                        unique=True,
                    ),
                ),
                (
                    "panel",
                    models.TextField(help_text="Name of LD panel used (eg 1000G)"),
                ),
                (
                    "population",
                    models.TextField(help_text="Name of population (eg EUR)"),
                ),
                (
                    "genome_build",
                    models.TextField(
                        choices=[("GRCh37", "GRCh37"), ("GRCh38", "GRCh38")]
                    ),
                ),
                (
                    "ld_data",
                    models.TextField(
                        help_text="Absolute path to PLINK formatted LD data (relative to at least key signal SNPs). Must be compressed with bgzip",
                        verbose_name="LD data",
                    ),
                ),
                (
                    "ld_data_tbi",
                    models.TextField(
                        help_text="Absolute path to Tabix index for the LD data. Must match the bgzip file",
                        verbose_name="LD tabix index",
                    ),
                ),
                (
                    "data_submission",
                    models.ForeignKey(
                        help_text="Data submission that this LD data was provided with",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.datasubmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeadVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vid",
                    models.TextField(
                        help_text="Full variant ID in chr_pos_ref_alt format."
                    ),
                ),
                ("chrom", models.TextField(db_collation="uint")),
                (
                    "pos",
                    models.PositiveIntegerField(
                        help_text="Position of the variant in the genome"
                    ),
                ),
                ("ref", models.TextField(help_text="Reference allele")),
                (
                    "alt",
                    models.TextField(
                        help_text="Alternate allele. This must also be the effect allele."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orcid",
                    models.TextField(help_text="ORCID of the analyst", unique=True),
                ),
                ("name", models.TextField(help_text="Name of the analyst")),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the analyst", max_length=254
                    ),
                ),
                (
                    "institution",
                    models.TextField(
                        blank=True, help_text="Institution of the analyst", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Phenotype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.TextField(
                        db_index=True,
                        help_text="Universally unique identifier",
                        unique=True,
                    ),
                ),
                (
                    "efo_id",
                    models.TextField(
                        help_text='External ID in EFO for the trait, e.g. "EFO_0001360" or "MONDO_0005148"',
                        null=True,
                    ),
                ),
                (
                    "kp_id",
                    models.TextField(
                        help_text='External ID in AMP knowledge portal for the trait, e.g. "T2DadjBMI"',
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text='Full name of the trait, e.g. "Body Mass Index" or "Fasting glucose adjusted for BMI"'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.TextField(
                        db_index=True,
                        help_text="A stable unique identifier for this entity. Should be specified on ingest.",
                        unique=True,
                    ),
                ),
                (
                    "pmid",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="PubMed ID for the publication",
                        null=True,
                    ),
                ),
                (
                    "doi",
                    models.TextField(
                        blank=True,
                        db_index=True,
                        help_text="Digital Object Identifier for the publication",
                        null=True,
                    ),
                ),
                (
                    "authors",
                    models.TextField(
                        help_text='Free-text author list, eg "ACRONYM Consortium" or "Mendel et al" (used for display only)',
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True, help_text="Title of the publication", null=True
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Year of publication", null=True
                    ),
                ),
                (
                    "journal",
                    models.TextField(
                        blank=True, help_text="Journal of publication", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.TextField(
                        db_index=True,
                        help_text="A stable unique identifier for this entity. Should be specified on ingest.",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text='A description of the study, e.g. "Global Lipids Genetics Consortium"',
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.TextField(
                        db_index=True,
                        help_text="Universally unique identifier",
                        unique=True,
                    ),
                ),
                (
                    "biomarker_type",
                    models.TextField(
                        help_text="Type of biomarker, e.g. phenotype or gene-expression exon-expression or methylation or atac-seq"
                    ),
                ),
                (
                    "exon",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait",
                        to="core.exon",
                    ),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait",
                        to="core.gene",
                    ),
                ),
                (
                    "phenotype",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait",
                        to="core.phenotype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarginalAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.TextField(
                        db_index=True,
                        help_text="A stable unique identifier for this analysis",
                        unique=True,
                    ),
                ),
                (
                    "analysis_type",
                    models.TextField(
                        choices=[("GWAS", "GWAS"), ("eQTL", "eQTL")],
                        help_text="Type of association analysis - GWAS, eQTL, pQTL, ATAC-seq, methylation, etc.",
                    ),
                ),
                (
                    "genome_build",
                    models.TextField(
                        choices=[("GRCh37", "GRCh37"), ("GRCh38", "GRCh38")],
                        help_text="Genome build used for this analysis (positions of variants)",
                    ),
                ),
                (
                    "tissue",
                    models.TextField(
                        blank=True,
                        help_text='Tissue or cell type in which this analysis\' trait was analyzed, e.g. "adipose" or "liver"',
                        null=True,
                    ),
                ),
                (
                    "ancestry",
                    models.TextField(
                        blank=True,
                        help_text='Ancestry of the samples used in this analysis, e.g. "EUR"',
                        null=True,
                    ),
                ),
                (
                    "summary_stats",
                    models.TextField(
                        help_text="Absolute path to the marginal summary stats for this study. Must be compressed with bgzip",
                        verbose_name="Marginal summary stats",
                    ),
                ),
                (
                    "summary_stats_tbi",
                    models.TextField(
                        help_text="Absolute path to Tabix index for summary stats (.tbi file). Must match bgzip file.",
                        verbose_name="Tabix index for summary stats",
                    ),
                ),
                (
                    "manhattan_bins",
                    models.TextField(
                        help_text="Absolute path to results of manhattan plot binning process",
                        verbose_name="Binned data for manhattan plots",
                    ),
                ),
                (
                    "qq_bins",
                    models.TextField(
                        help_text="Absolute path to results of manhattan plot binning process",
                        verbose_name="Binned data for QQ plots",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Freetext with important info such as analysis parameters. In the future, some parameters might be tracked as part of the DB schema."
                    ),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True,
                        help_text="URL for where the data was downloaded from. Used to track provenance.",
                        null=True,
                    ),
                ),
                (
                    "data_submission",
                    models.ForeignKey(
                        help_text="Analysis was part of this data submission",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.datasubmission",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        help_text="Analysis was part of this dataset",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.dataset",
                    ),
                ),
                (
                    "ld",
                    models.ForeignKey(
                        help_text="LD panel to be used with this dataset",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ldstats",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        help_text="The publication describing this analysis",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.publication",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        help_text="The study that produced this analysis",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.study",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        help_text="The trait analyzed in this analysis",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.trait",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FineMappedSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.TextField(
                        db_index=True,
                        help_text="A stable unique identifier for this entity. Should be specified on ingest",
                        unique=True,
                    ),
                ),
                (
                    "cond_analysis",
                    models.TextField(
                        help_text='Absolute path to conditional (or "all but one") analysis of marginal results (rel to lead variant of this signal)',
                        verbose_name="Cond analysis results",
                    ),
                ),
                (
                    "cond_analysis_tbi",
                    models.TextField(
                        help_text="Absolute path to Tabix index; must match the conditional analysis file",
                        verbose_name="tbi for cond results",
                    ),
                ),
                (
                    "neg_log_p",
                    models.FloatField(
                        help_text="Conditional or fine-mapped -log10p value."
                    ),
                ),
                (
                    "effect_marg",
                    models.FloatField(help_text="Effect size in the marginal analysis"),
                ),
                (
                    "effect_cond",
                    models.FloatField(
                        help_text="Effect size in the conditional/fine-mapping analysis"
                    ),
                ),
                (
                    "se_cond",
                    models.FloatField(
                        help_text="Conditional standard error of the effect size"
                    ),
                ),
                (
                    "cond_minp_variant",
                    models.TextField(
                        help_text="Variant with the smallest p-value after conditional analysis. Often the lead_variant* fields abovepertain to the variant that was reported in a GWAS publication, but that does not necessarily meanthat variant will also be the most significant in the conditional analysis.",
                        null=True,
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        help_text="The analysis in which this signal was identified",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.marginalanalysis",
                    ),
                ),
                (
                    "lead_variant",
                    models.ForeignKey(
                        help_text="Lead variant of the fine-mapped signal.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.leadvariant",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="The program used to perform the fine-mapping or conditional analysis",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.finemappingprogram",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exon",
            name="gene",
            field=models.ForeignKey(
                help_text="The gene to which this exon belongs",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exons",
                to="core.gene",
            ),
        ),
        migrations.AddField(
            model_name="datasubmission",
            name="publication",
            field=models.ForeignKey(
                help_text="Publication describing this overall data submission",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.publication",
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="analysts",
            field=models.ManyToManyField(
                help_text="Analysts who created this dataset",
                related_name="datasets_as_analyst",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="data_submission",
            field=models.ForeignKey(
                help_text="Data submission that this dataset belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.datasubmission",
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="principal_investigators",
            field=models.ManyToManyField(
                help_text="Principal investigators of the study that produced this dataset",
                related_name="datasets_as_pi",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="publication",
            field=models.ForeignKey(
                help_text="Publication describing this overall dataset",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.publication",
            ),
        ),
        migrations.AddField(
            model_name="dataset",
            name="submitter",
            field=models.ForeignKey(
                help_text="Person who submitted this dataset to the site",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datasets_as_submitter",
                to="core.person",
            ),
        ),
        migrations.CreateModel(
            name="ColocResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        help_text="A stable unique identifier for this entity. Should be specified on ingest.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "cross_signal",
                    models.JSONField(
                        help_text="Contains information about each signal and its lead variant's effect in the other signal's summary statistics",
                        null=True,
                    ),
                ),
                (
                    "coloc_h3",
                    models.FloatField(
                        help_text="Probability that both traits are associated, but with different causal variants",
                        verbose_name="H3",
                    ),
                ),
                (
                    "coloc_h4",
                    models.FloatField(
                        help_text="Probability that both traits are associated, with same causal variant",
                        verbose_name="H4",
                    ),
                ),
                (
                    "r2",
                    models.FloatField(
                        help_text="R2 between the two signals' lead variants", null=True
                    ),
                ),
                (
                    "n_coloc_between_traits",
                    models.PositiveIntegerField(
                        help_text="Number of colocalizations in total between the two traits for this gene or locus in the overall dataset",
                        null=True,
                    ),
                ),
                (
                    "data_submission",
                    models.ForeignKey(
                        help_text="This signal was identified as part of a specific bulk colocalization analysis",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.datasubmission",
                    ),
                ),
                (
                    "signal1",
                    models.ForeignKey(
                        help_text="The first signal (from trait 1)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.finemappedsignal",
                    ),
                ),
                (
                    "signal2",
                    models.ForeignKey(
                        help_text="The second signal (from trait 2)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.finemappedsignal",
                    ),
                ),
            ],
        ),
    ]
