# Generated by Django 3.2.13 on 2024-01-19 03:20

import colocus.core.file_util
import colocus.utils.storages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(help_text='A stable unique identifier for this dataset, should be specified on ingest', unique=True)),
                ('description', models.TextField(blank=True, help_text='A human-readable description of the dataset, like "Colocalization & fine-mapping of adipose eQTLs"', null=True)),
                ('ingest_date', models.DateTimeField(auto_now_add=True, help_text='Date when this dataset was loaded into the site', null=True)),
                ('authors', models.TextField(help_text='Free-text author list, eg "ACRONYM Consortium" or "Mendel et al" (used for display only)')),
                ('contact_email', models.EmailField(blank=True, help_text='Contact of record to report problems / questions about this data submission', max_length=254, null=True)),
                ('pmid', models.TextField(blank=True, help_text='PubMed ID for a publication describing this overall set of data', null=True, verbose_name='PMID')),
            ],
        ),
        migrations.CreateModel(
            name='Exon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ens_id', models.TextField(db_index=True, help_text='Ensembl ID of the exon, or Ensembl ID of the gene + exon coordinates, e.g. ENSG00000141510.15_1_100', unique=True)),
                ('chrom', models.TextField(help_text='Chromosome', null=True)),
                ('start', models.PositiveIntegerField(help_text='Start position of the exon', null=True)),
                ('end', models.PositiveIntegerField(help_text='End position of the exon', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FineMappingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the fine-mapping program, e.g. "SuSiE" or "FINEMAP"')),
                ('version', models.TextField(help_text='Version of the fine-mapping program, e.g. "v1.0.0"')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ens_id', models.TextField(db_index=True, help_text='Ensembl ID', unique=True)),
                ('symbol', models.TextField(db_index=True, help_text='HGNC symbol')),
                ('chrom', models.TextField(help_text='Chromosome', null=True)),
                ('start', models.PositiveIntegerField(help_text='Start position of the gene', null=True)),
                ('end', models.PositiveIntegerField(help_text='End position of the gene', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LDStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(db_index=True, help_text='A stable unique identifier for this entity. Should be specified on ingest.', unique=True)),
                ('panel', models.TextField(help_text='Name of LD panel used (eg 1000G)')),
                ('population', models.TextField(help_text='Name of population (eg EUR)')),
                ('genome_build', models.TextField(choices=[('GRCh37', 'GRCh37'), ('GRCh38', 'GRCh38')])),
                ('ld_data', models.FileField(help_text='PLINK formatted LD data (relative to at least key signal SNPs). Must be compressed with bgzip', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_ld_filename, verbose_name='LD data')),
                ('ld_data_tbi', models.FileField(help_text='Tabix index for the LD data. Must match the bgzip file', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_ld_filename_tbi, verbose_name='LD tabix index')),
                ('data_submission', models.ForeignKey(help_text='Data submission that this LD data was provided with', on_delete=django.db.models.deletion.CASCADE, to='core.datasubmission')),
            ],
        ),
        migrations.CreateModel(
            name='LeadVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.TextField(help_text='Full variant ID in chr_pos_ref_alt format.')),
                ('chrom', models.TextField(db_collation='uint')),
                ('pos', models.PositiveIntegerField(help_text='Position of the variant in the genome')),
                ('ref', models.TextField(help_text='Reference allele')),
                ('alt', models.TextField(help_text='Alternate allele. This must also be the effect allele.')),
            ],
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efo_id', models.TextField(help_text='External ID in EFO for the trait, e.g. "EFO_0001360" or "MONDO_0005148"', unique=True)),
                ('name', models.TextField(help_text='Full name of the trait, e.g. "Body Mass Index" or "Fasting glucose adjusted for BMI"')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.PositiveIntegerField(db_index=True, help_text='PubMed ID for the publication', unique=True)),
                ('authors', models.TextField(help_text='Free-text author list, eg "ACRONYM Consortium" or "Mendel et al" (used for display only)', null=True)),
                ('title', models.TextField(help_text='Title of the publication', null=True)),
                ('year', models.PositiveIntegerField(help_text='Year of publication', null=True)),
                ('journal', models.TextField(help_text='Journal of publication', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(db_index=True, help_text='A stable unique identifier for this entity. Should be specified on ingest.', unique=True)),
                ('description', models.TextField(blank=True, help_text='A description of the study, e.g. "Global Lipids Genetics Consortium"', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(db_index=True, help_text='Universally unique identifier', unique=True)),
                ('biomarker_type', models.TextField(help_text='Type of biomarker, e.g. phenotype or gene-expression exon-expression or methylation or atac-seq')),
                ('tissue', models.TextField(blank=True, help_text='Tissue or cell type in which the trait was analyzed, e.g. "adipose" or "liver"', null=True)),
                ('exon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trait', to='core.exon')),
                ('gene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trait', to='core.gene')),
                ('phenotype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trait', to='core.phenotype')),
            ],
        ),
        migrations.CreateModel(
            name='MarginalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(db_index=True, help_text='A stable unique identifier for this analysis', unique=True)),
                ('analysis_type', models.TextField(choices=[('gwas', 'GWAS'), ('eqtl', 'eQTL')], help_text='Type of association analysis - GWAS, eQTL, pQTL, ATAC-seq, methylation, etc.')),
                ('genome_build', models.TextField(choices=[('GRCh37', 'GRCh37'), ('GRCh38', 'GRCh38')], help_text='Genome build used for this analysis (positions of variants)')),
                ('summary_stats', models.FileField(help_text='The marginal summary stats for this study. Must be compressed with bgzip', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_marginal_summstats, verbose_name='Marginal summary stats')),
                ('summary_stats_tbi', models.FileField(help_text='Tabix index for summary stats (.tbi file). Must match bgzip file.', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_marginal_summstats_tbi, verbose_name='Tabix index for summary stats')),
                ('manhattan_bins', models.FileField(help_text='Results of manhattan plot binning process', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_manhattan, verbose_name='Binned data for manhattan plots')),
                ('qq_bins', models.FileField(help_text='Results of manhattan plot binning process', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_qq, verbose_name='Binned data for QQ plots')),
                ('description', models.TextField(help_text='Freetext with important info such as analysis parameters. In the future, some parameters might be tracked as part of the DB schema.')),
                ('external_link', models.URLField(blank=True, help_text='URL for where the data was downloaded from. Used to track provenance.', null=True)),
                ('data_submission', models.ForeignKey(help_text='Analysis was part of this data submission', on_delete=django.db.models.deletion.CASCADE, to='core.datasubmission')),
                ('ld', models.ForeignKey(help_text='LD panel to be used with this dataset', on_delete=django.db.models.deletion.CASCADE, to='core.ldstats')),
                ('publication', models.ForeignKey(help_text='The publication describing this analysis', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.publication')),
                ('study', models.ForeignKey(help_text='The study that produced this analysis', on_delete=django.db.models.deletion.CASCADE, to='core.study')),
                ('trait', models.ForeignKey(help_text='The trait analyzed in this analysis', on_delete=django.db.models.deletion.CASCADE, to='core.trait')),
            ],
        ),
        migrations.CreateModel(
            name='FineMappedSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(db_index=True, help_text='A stable unique identifier for this entity. Should be specified on ingest', unique=True)),
                ('cond_analysis', models.FileField(help_text='Conditional (or "all but one") analysis of marginal results (rel to lead variant of this signal)', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_signals_cond, verbose_name='Cond analysis results ')),
                ('cond_analysis_tbi', models.FileField(help_text='Tabix index; must match the conditional analysis file', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_signals_cond_tbi, verbose_name='tbi for cond results')),
                ('neg_log_p', models.FloatField(help_text='Conditional or fine-mapped -log10p value.')),
                ('effect_marg', models.FloatField(help_text='Effect size in the marginal analysis')),
                ('effect_cond', models.FloatField(help_text='Effect size in the conditional/fine-mapping analysis')),
                ('se_cond', models.FloatField(help_text='Conditional standard error of the effect size')),
                ('cond_minp_variant', models.TextField(help_text='Variant with the smallest p-value after conditional analysis. Often the lead_variant* fields abovepertain to the variant that was reported in a GWAS publication, but that does not necessarily meanthat variant will also be the most significant in the conditional analysis.', null=True)),
                ('analysis', models.ForeignKey(help_text='The analysis in which this signal was identified', on_delete=django.db.models.deletion.CASCADE, to='core.marginalanalysis')),
                ('lead_variant', models.ForeignKey(help_text='Lead variant of the fine-mapped signal.', on_delete=django.db.models.deletion.CASCADE, to='core.leadvariant')),
                ('program', models.ForeignKey(help_text='The program used to perform the fine-mapping or conditional analysis', on_delete=django.db.models.deletion.CASCADE, to='core.finemappingprogram')),
            ],
        ),
        migrations.AddField(
            model_name='exon',
            name='gene',
            field=models.ForeignKey(help_text='The gene to which this exon belongs', on_delete=django.db.models.deletion.CASCADE, related_name='exons', to='core.gene'),
        ),
        migrations.CreateModel(
            name='ColocResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, help_text='A stable unique identifier for this entity. Should be specified on ingest.', max_length=32, unique=True)),
                ('cross_signal', models.JSONField(help_text="Contains information about each signal and its lead variant's effect in the other signal's summary statistics", null=True)),
                ('coloc_h3', models.FloatField(help_text='Probability that both traits are associated, but with different causal variants', verbose_name='H3')),
                ('coloc_h4', models.FloatField(help_text='Probability that both traits are associated, with same causal variant', verbose_name='H4')),
                ('r2', models.FloatField(help_text="R2 between the two signals' lead variants", null=True)),
                ('n_coloc_between_traits', models.PositiveIntegerField(help_text='Number of colocalizations in total between the two traits for this gene or locus in the overall dataset', null=True)),
                ('data_submission', models.ForeignKey(help_text='This signal was identified as part of a specific bulk colocalization analysis', on_delete=django.db.models.deletion.CASCADE, to='core.datasubmission')),
                ('signal1', models.ForeignKey(help_text='The first signal (from trait 1)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.finemappedsignal')),
                ('signal2', models.ForeignKey(help_text='The second signal (from trait 2)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.finemappedsignal')),
            ],
        ),
    ]
