# Generated by Django 3.2.13 on 2022-06-23 21:45

import colocus.core.file_util
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(help_text='A stable unique identifier for this dataset, should be specified on ingest', max_length=32, unique=True)),
                ('study_name', models.CharField(db_index=True, help_text='Name of the parent study (like "GLGC" or "GTEx") that produced the colocalization analysis', max_length=100)),
                ('ingest_complete', models.DateTimeField(auto_now_add=True, help_text='Date when this dataset was loaded into the site', null=True)),
                ('study_date', models.DateField(help_text='Author provided date when the analysis was performed')),
                ('authors', models.TextField(help_text='Free-text author list, eg "ACRONYM Consortium" or "Mendel et al" (used for display only)')),
                ('contact_email', models.EmailField(blank=True, help_text='Contact of record to report problems / questions about this analysis', max_length=254, null=True)),
                ('pmid', models.CharField(blank=True, help_text='Identify a publication describing this colocalization analysis', max_length=20, null=True, verbose_name='PMID')),
            ],
        ),
        migrations.CreateModel(
            name='LDPairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(help_text='A stable unique identifier for this entity. Should be specified on ingest.', max_length=32, unique=True)),
                ('panel', models.CharField(help_text='Name of LD panel used (eg 1000G)', max_length=32)),
                ('population', models.CharField(help_text='Name of population (eg EUR)', max_length=32)),
                ('genome_build', models.CharField(choices=[('GRCh37', 'GRCh37'), ('GRCh38', 'GRCh38')], max_length=10)),
                ('ld_data', models.FileField(help_text='PLINK formatted LD data (relative to at least key signal SNPs). Must be compressed with bgzip', upload_to=colocus.core.file_util.get_ld_filename, verbose_name='LD data')),
                ('ld_data_tbi', models.FileField(help_text='Tabix index for the LD data. Must match the bgzip file', upload_to=colocus.core.file_util.get_ld_filename_tbi, verbose_name='LD tabix index')),
                ('analysis', models.ForeignKey(help_text='This LD was provided for a specific analysis', on_delete=django.db.models.deletion.CASCADE, to='core.analysisgroup')),
            ],
        ),
        migrations.CreateModel(
            name='MarginalTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(help_text='A stable unique identifier for this entity. Should be specified on ingest', max_length=32, unique=True)),
                ('trait_type', models.CharField(choices=[('GWAS', 'GWAS'), ('eQTL', 'eQTL')], max_length=10)),
                ('genome_build', models.CharField(choices=[('GRCh37', 'GRCh37'), ('GRCh38', 'GRCh38')], max_length=10)),
                ('metadata', models.JSONField(help_text='Additional trait-type specific information. Eg {trait} for GWAS, or { gene, tissue } for eQTL')),
                ('summary_stats', models.FileField(help_text='The marginal summary stats for this study. Must be compressed with bgzip', upload_to=colocus.core.file_util.get_marginal_summstats, verbose_name='Marginal summary stats')),
                ('summary_stats_tbi', models.FileField(help_text='Tabix index for summary stats (.tbi file). Must match bgzip file.', upload_to=colocus.core.file_util.get_marginal_summstats_tbi, verbose_name='Tabix index for summary stats')),
                ('manhattan_bins', models.FileField(help_text='Results of manhattan plot binning process', upload_to=colocus.core.file_util.get_manhattan, verbose_name='Binned data for manhattan plots')),
                ('qq_bins', models.FileField(help_text='Results of manhattan plot binning process', upload_to=colocus.core.file_util.get_qq, verbose_name='Binned data for QQ plots')),
                ('study_name', models.CharField(db_index=True, help_text='Name of the parent study (like "GLGC" or "GTEx") that produced the dataset', max_length=100)),
                ('label', models.TextField(help_text='A human-readable description of the dataset, like "Body Mass Index"')),
                ('description', models.TextField(help_text='Freetext with important info such as analysis parameters. In the future, some parameters might be tracked as part of the DB schema.')),
                ('pmid', models.CharField(blank=True, help_text='The publication describing this trait analysis', max_length=20, null=True, verbose_name='PMID')),
                ('authors', models.TextField(help_text='Free-text author list, eg "ACRONYM Consortium" or "Mendel et al" (used for display only)')),
                ('external_link', models.URLField(blank=True, help_text='URL for where the data was downloaded from. Used to track provenance.', null=True)),
                ('ld', models.ForeignKey(help_text='The LD panel/ population corresponding to this dataset', on_delete=django.db.models.deletion.CASCADE, to='core.ldpairs')),
            ],
        ),
        migrations.CreateModel(
            name='MarginalSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(help_text='A stable unique identifier for this entity. Should be specified on ingest', max_length=32, unique=True)),
                ('cond_analysis', models.FileField(help_text='Conditional (or "all but one") analysis of marginal results (rel to lead variant of this signal)', upload_to=colocus.core.file_util.get_signals_cond, verbose_name='Cond analysis results ')),
                ('cond_analysis_tbi', models.FileField(help_text='Tabix index; must match the conditional analysis file', upload_to=colocus.core.file_util.get_signals_cond_tbi, verbose_name='tbi for cond results')),
                ('lead_variant_chrom', models.CharField(max_length=5)),
                ('lead_variant_pos', models.PositiveIntegerField()),
                ('lead_variant_marker', models.CharField(help_text='Specifier of the form chrom:pos_ref/alt. Used for display only', max_length=5)),
                ('lead_variant_neg_log_p', models.FloatField(help_text='Marginal -log10p value for lead variant. Used for display purposes.')),
                ('lead_variant_nearest_gene', models.CharField(help_text='Human-friendly name of the closest gene. Used for display purposes.', max_length=50)),
                ('analysis', models.ForeignKey(help_text='This signal was identified as part of a specific bulk colocalization analysis', on_delete=django.db.models.deletion.CASCADE, to='core.analysisgroup')),
                ('trait', models.ForeignKey(help_text='The trait in which this signal was identified', on_delete=django.db.models.deletion.CASCADE, to='core.marginaltrait')),
            ],
        ),
        migrations.CreateModel(
            name='ColocResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(help_text='A stable unique identifier for this entity. Should be specified on ingest.', max_length=32, unique=True)),
                ('coloc_h3', models.FloatField(help_text='Probability that both traits are associated, but with different causal variants', verbose_name='H3')),
                ('coloc_h4', models.FloatField(help_text='Probability that both traits are associated, with same causal variant', verbose_name='H4')),
                ('analysis', models.ForeignKey(help_text='This signal was identified as part of a specific bulk colocalization analysis', on_delete=django.db.models.deletion.CASCADE, to='core.analysisgroup')),
                ('signal1', models.ForeignKey(help_text='The first signal (from trait 1)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.marginalsignal')),
                ('signal2', models.ForeignKey(help_text='The second signal (from trait 2)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.marginalsignal')),
            ],
        ),
    ]
