# Generated by Django 4.2.9 on 2024-02-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phenotype",
            name="kp_id",
            field=models.TextField(
                default="",
                help_text='External ID in AMP knowledge portal for the trait, e.g. "T2DadjBMI"',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phenotype",
            name="uuid",
            field=models.TextField(
                db_index=True,
                default="",
                help_text="Universally unique identifier",
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publication",
            name="doi",
            field=models.TextField(
                blank=True,
                db_index=True,
                help_text="Digital Object Identifier for the publication",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="phenotype",
            name="efo_id",
            field=models.TextField(
                help_text='External ID in EFO for the trait, e.g. "EFO_0001360" or "MONDO_0005148"'
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="journal",
            field=models.TextField(
                blank=True, help_text="Journal of publication", null=True
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="pmid",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="PubMed ID for the publication",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.TextField(
                blank=True, help_text="Title of the publication", null=True
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, help_text="Year of publication", null=True
            ),
        ),
    ]
