# Generated by Django 4.2.9 on 2025-04-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finemappedsignal",
            name="is_marg",
            field=models.BooleanField(
                default=False,
                help_text="True if this signal's summary statistics are from the marginal analysis, not a conditional analysis.This can happen in cases where the marginal analysis is the only analysis (no conditional analysis was needed), or if there was a problem in fine-mapping at this particular locus",
            ),
        ),
        migrations.AlterField(
            model_name="marginalanalysis",
            name="dataset",
            field=models.ForeignKey(
                help_text="Analysis was part of this dataset",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marginal_analyses",
                to="core.dataset",
            ),
        ),
    ]
