# Generated by Django 3.2.13 on 2022-08-15 19:21

import colocus.core.file_util
import colocus.utils.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldpairs',
            name='ld_data',
            field=models.FileField(help_text='PLINK formatted LD data (relative to at least key signal SNPs). Must be compressed with bgzip', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_ld_filename, verbose_name='LD data'),
        ),
        migrations.AlterField(
            model_name='ldpairs',
            name='ld_data_tbi',
            field=models.FileField(help_text='Tabix index for the LD data. Must match the bgzip file', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_ld_filename_tbi, verbose_name='LD tabix index'),
        ),
        migrations.AlterField(
            model_name='marginalsignal',
            name='cond_analysis',
            field=models.FileField(help_text='Conditional (or "all but one") analysis of marginal results (rel to lead variant of this signal)', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_signals_cond, verbose_name='Cond analysis results '),
        ),
        migrations.AlterField(
            model_name='marginalsignal',
            name='cond_analysis_tbi',
            field=models.FileField(help_text='Tabix index; must match the conditional analysis file', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_signals_cond_tbi, verbose_name='tbi for cond results'),
        ),
        migrations.AlterField(
            model_name='marginaltrait',
            name='manhattan_bins',
            field=models.FileField(help_text='Results of manhattan plot binning process', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_manhattan, verbose_name='Binned data for manhattan plots'),
        ),
        migrations.AlterField(
            model_name='marginaltrait',
            name='qq_bins',
            field=models.FileField(help_text='Results of manhattan plot binning process', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_qq, verbose_name='Binned data for QQ plots'),
        ),
        migrations.AlterField(
            model_name='marginaltrait',
            name='summary_stats',
            field=models.FileField(help_text='The marginal summary stats for this study. Must be compressed with bgzip', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_marginal_summstats, verbose_name='Marginal summary stats'),
        ),
        migrations.AlterField(
            model_name='marginaltrait',
            name='summary_stats_tbi',
            field=models.FileField(help_text='Tabix index for summary stats (.tbi file). Must match bgzip file.', storage=colocus.utils.storages.OverwriteStorage(), upload_to=colocus.core.file_util.get_marginal_summstats_tbi, verbose_name='Tabix index for summary stats'),
        ),
        migrations.AlterField(
            model_name='marginaltrait',
            name='trait_type',
            field=models.CharField(choices=[('gwas', 'GWAS'), ('eQTL', 'eQTL')], max_length=10),
        ),
    ]
