# Generated by Django 3.2.13 on 2022-08-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220815_1921'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='colocresult',
            index=models.Index(fields=['analysis', 'uuid'], name='Coloc-in-study index'),
        ),
        migrations.AddIndex(
            model_name='ldpairs',
            index=models.Index(fields=['analysis', 'uuid'], name='LD-in-study index'),
        ),
        migrations.AddIndex(
            model_name='marginalsignal',
            index=models.Index(fields=['analysis', 'uuid'], name='Signal-in-study index'),
        ),
        migrations.AddIndex(
            model_name='marginaltrait',
            index=models.Index(fields=['analysis', 'uuid'], name='Trait-in-study index'),
        ),
    ]
