# Generated by Django 4.2.9 on 2024-02-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_phenotype_kp_id_phenotype_uuid_publication_doi_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="tissue",
        ),
        migrations.AddField(
            model_name="marginalanalysis",
            name="tissue",
            field=models.TextField(
                blank=True,
                help_text='Tissue or cell type in which this analysis\' trait was analyzed, e.g. "adipose" or "liver"',
                null=True,
            ),
        ),
    ]
