# Generated by Django 4.2.9 on 2024-08-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_trait_tissue_marginalanalysis_tissue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finemappingprogram",
            name="version",
            field=models.TextField(
                help_text='Version of the fine-mapping program, e.g. "v1.0.0"',
                null=True,
            ),
        ),
    ]
