# Generated by Django 3.2.13 on 2022-10-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220830_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginalsignal',
            name='lead_variant_assoc_gene',
            field=models.CharField(blank=True, help_text='Gene associated with lead variant (Ensembl ID / ENSG).', max_length=50),
        ),
        migrations.AddField(
            model_name='marginalsignal',
            name='lead_variant_assoc_gene_symbol',
            field=models.CharField(blank=True, help_text='Gene associated with lead variant (HGNC symbol.)', max_length=50),
        ),
    ]
