# Generated by Django 4.2.9 on 2025-06-16 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_dataset_cell_type_marginalanalysis_cell_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasubmission",
            name="data_hash",
            field=models.CharField(
                default="",
                help_text="A hash of the data files used to generate this submission, used to verify data integrity.",
                max_length=64,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datasubmission",
            name="data_hash_type",
            field=models.CharField(
                choices=[("B3SUM", "b3sum")],
                default="",
                help_text="Type of hash used to generate the data_hash, e.g., 'b3sum'",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datasubmission",
            name="data_version",
            field=models.CharField(
                default="",
                help_text="Version of the data, should be vX.X.X format.",
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Version must be in vX.X.X format (e.g., v1.2.3 or v1.2.3-beta)",
                        regex="^v\\d+\\.\\d+\\.\\d+(-\\w+)?$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datasubmission",
            name="pipeline_remote",
            field=models.TextField(
                default="",
                help_text="Git remote URL of the pipeline used to generate this data",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datasubmission",
            name="pipeline_version",
            field=models.CharField(
                default="",
                help_text="Version of the pipeline used to generate this data, should be vX.X.X format.",
                max_length=32,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Version must be in vX.X.X format (e.g., v1.2.3 or v1.2.3-beta)",
                        regex="^v\\d+\\.\\d+\\.\\d+(-\\w+)?$",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
