# Generated by Django 4.2.9 on 2024-08-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_finemappingprogram_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phenotype",
            name="efo_id",
            field=models.TextField(
                help_text='External ID in EFO for the trait, e.g. "EFO_0001360" or "MONDO_0005148"',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="phenotype",
            name="kp_id",
            field=models.TextField(
                help_text='External ID in AMP knowledge portal for the trait, e.g. "T2DadjBMI"',
                null=True,
            ),
        ),
    ]
