# Generated by Django 3.2.13 on 2022-10-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221004_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marginalsignal',
            name='lead_variant_assoc_gene_symbol',
        ),
        migrations.AddField(
            model_name='marginalsignal',
            name='lead_variant_assoc_gene_ensg',
            field=models.CharField(blank=True, help_text='Gene associated with lead variant (Ensembl ENSG ID).', max_length=50),
        ),
        migrations.AlterField(
            model_name='marginalsignal',
            name='lead_variant_assoc_gene',
            field=models.CharField(blank=True, help_text='Gene associated with lead variant (HGNC symbol).', max_length=50),
        ),
    ]
