# Generated by Django 4.2.9 on 2025-09-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_datasubmission_data_hash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finemappedsignal",
            name="cs_alpha",
            field=models.JSONField(
                default=list,
                help_text="List of posterior inclusion probabilities (conditional on this signal) for each variant in the credible set.",
            ),
        ),
        migrations.AddField(
            model_name="finemappedsignal",
            name="cs_variants",
            field=models.JSONField(
                default=list,
                help_text="List of variants in this signal's credible set.",
            ),
        ),
    ]
