# Generated by Django 4.2.9 on 2024-09-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_phenotype_efo_id_alter_phenotype_kp_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="uuid",
            field=models.TextField(
                db_index=True,
                default=0,
                help_text="A stable unique identifier for this entity. Should be specified on ingest.",
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="marginalanalysis",
            name="analysis_type",
            field=models.TextField(
                choices=[("GWAS", "GWAS"), ("eQTL", "eQTL")],
                help_text="Type of association analysis - GWAS, eQTL, pQTL, ATAC-seq, methylation, etc.",
            ),
        ),
    ]
