# Generated by Django 3.2.13 on 2022-10-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221004_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginalsignal',
            name='lead_variant_chrom',
            field=models.CharField(db_collation='UINT', max_length=5),
        ),
    ]
