# Generated by Django 4.2.9 on 2025-11-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_colocresult_with_orphans"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColocResultWithOrphans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        help_text="A stable unique identifier for this entity. Should be specified on ingest.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "cross_signal",
                    models.JSONField(
                        help_text="Contains information about each signal and its lead variant's effect in the other signal's summary statistics",
                        null=True,
                    ),
                ),
                (
                    "coloc_h3",
                    models.FloatField(
                        help_text="Probability that both traits are associated, but with different causal variants",
                        verbose_name="H3",
                    ),
                ),
                (
                    "coloc_h4",
                    models.FloatField(
                        help_text="Probability that both traits are associated, with same causal variant",
                        verbose_name="H4",
                    ),
                ),
                (
                    "r2",
                    models.FloatField(
                        help_text="R2 between the two signals' lead variants", null=True
                    ),
                ),
                (
                    "n_coloc_between_traits",
                    models.PositiveIntegerField(
                        help_text="Number of colocalizations in total between the two traits for this gene or locus in the overall dataset",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "core_colocresult_with_orphans",
                "managed": False,
            },
        ),
    ]
