# Generated by Django 4.2.9 on 2024-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_publication_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="doi",
            field=models.TextField(
                blank=True,
                db_index=True,
                help_text="Digital Object Identifier for the publication",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="pmid",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="PubMed ID for the publication",
                null=True,
            ),
        ),
    ]
