# Generated by Django 3.2.13 on 2022-10-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_marginalsignal_lead_variant_chrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginalsignal',
            name='lead_variant_chrom',
            field=models.CharField(db_collation='uint', max_length=5),
        ),
    ]
