# Generated by Django 3.2.13 on 2022-10-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_marginalsignal_lead_variant_chrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginalsignal',
            name='lead_variant_alt',
            field=models.TextField(default='', help_text='Alternate allele of lead variant. This must also be the effect allele.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marginalsignal',
            name='lead_variant_effect',
            field=models.FloatField(default=0.0, help_text='Effect size of lead variant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marginalsignal',
            name='lead_variant_ref',
            field=models.TextField(default='', help_text='Reference allele of lead variant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marginalsignal',
            name='lead_variant_se',
            field=models.FloatField(default=0.0, help_text='Standard error of the effect size of the lead variant'),
            preserve_default=False,
        ),
    ]
