# Generated by Django 4.2.9 on 2025-12-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_metabolite_methylprobe_alter_dataset_analysis_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marginalanalysis",
            name="analysis_type",
            field=models.TextField(
                choices=[
                    ("GWAS", "GWAS"),
                    ("eQTL", "eQTL"),
                    ("mQTL", "mQTL"),
                    ("metabQTL", "metabQTL"),
                    ("pQTL", "pQTL"),
                ],
                db_index=True,
                help_text="Type of association analysis - GWAS, eQTL, pQTL, ATAC-seq, methylation, etc.",
            ),
        ),
    ]
