# Generated by Django 3.2.13 on 2023-02-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221027_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='colocresult',
            name='cross_signals',
            field=models.JSONField(default=None, help_text="Contains information about each signal and its lead variant's effect in the other signal's summary statistics"),
            preserve_default=False,
        ),
    ]
