# Generated by Django 4.2.9 on 2025-12-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_marginalanalysis_analysis_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="label",
            field=models.TextField(
                default="",
                help_text="Display label for tables in browser and for sorting",
            ),
            preserve_default=False,
        ),
    ]
