# Generated by Django 3.2.13 on 2023-02-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_colocresult_cross_signals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colocresult',
            name='cross_signals',
            field=models.JSONField(help_text="Contains information about each signal and its lead variant's effect in the other signal's summary statistics", null=True),
        ),
    ]
