# Generated by Django 3.2.13 on 2023-02-05 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_colocresult_cross_signals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colocresult',
            old_name='cross_signals',
            new_name='cross_signal',
        ),
    ]
