# Generated by Django 3.2.13 on 2023-03-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_cross_signals_colocresult_cross_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='colocresult',
            name='r2',
            field=models.FloatField(help_text="R2 between the two signals' lead variants", null=True),
        ),
    ]
