# Generated by Django 3.2.13 on 2023-03-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_colocresult_r2'),
    ]

    operations = [
        migrations.AddField(
            model_name='colocresult',
            name='n_coloc_between_traits',
            field=models.PositiveIntegerField(help_text='Number of colocalizations in total between the two traits for this gene or locus in the overall dataset', null=True),
        ),
    ]
