# Generated by Django 3.2.13 on 2023-03-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_colocresult_n_coloc_between_traits'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginalsignal',
            name='lead_variant_effect_marg',
            field=models.FloatField(default=0, help_text='Effect size of lead variant, in the marginal analysis'),
            preserve_default=False,
        ),
    ]
