# Generated by Django 3.2.13 on 2023-08-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_marginalsignal_lead_variant_effect_marg'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginalsignal',
            name='cond_minp_variant',
            field=models.TextField(help_text='Variant with the smallest p-value after conditional analysis. Often the lead_variant* fields abovepertain to the variant that was reported in a GWAS publication, but that does not necessarily meanthat variant will also be the most significant in the conditional analysis.', null=True),
        ),
    ]
