# Generated by Django 3.2.13 on 2023-08-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_marginalsignal_cond_minp_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisgroup',
            name='label',
            field=models.TextField(blank=True, help_text='A human-readable description of the dataset, like "GIANT BMI meta-analysis"', null=True),
        ),
    ]
