# Generated by Django 3.2.13 on 2023-11-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_analysisgroup_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginalsignal',
            name='lead_variant_assoc_exon',
            field=models.CharField(blank=True, help_text='Gene associated with lead variant (Ensembl ENSG ID).', max_length=50),
        ),
    ]
